export const PRODUCT_LIST_REQ = "PRODUCT_LIST_REQ" 
export const PRODUCT_LIST_REQ_SUCESS = "PRODUCT_LIST_REQ_SUCESS" 
export const PRODUCT_LIST_REQ_FAIL = "PRODUCT_LIST_REQ_FAIL" 


export const PRODUCT_DETAIL_REQ = "PRODUCT_DETAIL_REQ" 
export const PRODUCT_DETAIL_REQ_SUCESS = "PRODUCT_DETAIL_REQ_SUCESS" 
export const PRODUCT_DETAIL_REQ_FAIL = "PRODUCT_DETAIL_REQ_FAIL" 