export const USER_LOGIN_REQ = "USER_LOGIN_REQ";
export const USER_LOGIN_REQ_SUCCESS = "USER_LOGIN_REQ_SUCCESS";
export const USER_LOGIN_REQ_FAIL = "USER_LOGIN_REQ_FAIL";
export const USER_LOGOUT = "USER_LOGOUT";

export const USER_REGISTER_REQ = "USER_REGISTER_REQ";
export const USER_REGISTER_REQ_SUCCESS = "USER_REGISTER_REQ_SUCCESS";
export const USER_REGISTER_REQ_FAIL = "USER_REGISTER_REQ_FAIL";


export const USER_LIST_REQ = "USER_LIST_REQ";
export const USER_LIST_REQ_SUCCESS = "USER_LIST_REQ_SUCCESS";
export const USER_LIST_REQ_FAIL = "USER_LIST_REQ_FAIL";

export const USER_UPDATE_REQ = "USER_UPDATE_REQ";
export const USER_UPDATE_REQ_SUCCESS = "USER_UPDATE_REQ_SUCCESS";
export const USER_UPDATE_REQ_FAIL = "USER_UPDATE_REQ_FAIL";

export const USER_DELETE_REQ = "USER_DELETE_REQ";
export const USER_DELETE_REQ_SUCCESS = "USER_DELETE_REQ_SUCCESS";
export const USER_DELETE_REQ_FAIL = "USER_DELETE_REQ_FAIL";

